<div class="autorizacion">																																																							
    <div><label>Entidad:</label><?php echo $autorizacion[0]["entidad"]; ?></div>																			
    <div><label>Escuela:</label><?php echo $autorizacion[0]["escuela"]; ?></div>	
    <div><label>Licenciatura:</label><?php echo $autorizacion[0]["licenciatura"]; ?></div>					
    <div><label>Especialidad:</label><?php echo $autorizacion[0]["especialidad"]; ?></div>				
    <div><label>Autorizacion:</label><?php echo ($autorizacion[0]["autorizar"])?"Si":"No"; ?></div>		
    <div><label>Periodo:</label><?php echo $autorizacion[0]["periodo1"]; ?> - <?php echo $autorizacion[0]["periodo2"]; ?></div>
    <div><label>Oficio:</label><?php echo $autorizacion[0]["oficio"]; ?></div>															
</div>						