<?php
$this->headTitle("Login usuarios");
$form = $this->form;
$form->prepare();		
							 						                                   
$form->setAttributes(array(								
   	'action' => $this->url.'/AutorizarLicenciaturas/usuarios/login',
    'method' =>'post',
    'class'  =>'form-horizontal',
    'role'   =>'form'	               
));																													
																				
echo $this->form()->openTag($form);
?>			
<div class="login">						
	<div class="panel panel-default">		
		<div class="panel-heading">Acceso</div>
		<div class="panel-body">																												
				<div class="form-group">
				<?php 				
				    $login = $form->get('login');	
				?>   
				   	<label class="col-xs-5 control-label">Usuario:</label>
				   	<div class="col-xs-6">				
				<?php   	
				    echo $this->formInput($login);
				?>							
					</div>																																
				</div>																																
				<div class="form-group">
				<?php 											
				    $password = $form->get('password');
				?>   											
				   	<label class="col-xs-5 control-label">Contraseña:</label>
					<div class="col-xs-6">																				
				<?php 														    
				    echo $this->formInput($password);
				    echo $this->formElementErrors($password);
				?>									
					</div>																					
				</div>									
				<div class="form-group">				
			        <div class="col-xs-offset-5 col-xs-10">
			        	<?php 		
						echo $this->flashMessenger()->render();
						echo $this->formElement($form->get('submit'));
						echo $this->form()->closeTag();
						?>  										   
			        </div>												
			     </div>																													
		</div>
	</div>	
</div>	